### ISSUE TITLE
annotation conversion

### ISSUE THREAD

**Issue by liangxi627** [zhaobaiyu/visdrone#1]
Hello, how to convert the Visdrone-VID annotations into VOC format? Can you share the code, thank you!
And what's your mAP of Visdrone-VID dataset on YOLOv3？

**Comment by zhaobaiyu** [comment]
The script is [here](https://github.com/zhaobaiyu/visdrone/blob/master/darknet/scripts/visdrone_vid_transform.py).

**Comment by nankeermeng** [comment]
@zhaobaiyu @liangxi627 can you share your the whole code containing visdrone vid annotation conversion to voc xml? I make it following visdrone_vid_transform.py cannot transform it standard voc xml. I an a fresher, thanks your to guide me.
